# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'
hook_add = '''
  autocmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
