# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'
hook_add = '''
  autocmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev  = 'release'
if   = '''! filereadable(expand("~/.disablecoc"))'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'simeji/winresizer'

