general.live_config_reload = true

general.import = [
]

[font]
size=15

[font.normal]
 family = "SauceCodePro Nerd Font"
 style = "Regular"

[font.bold]
 family = "SauceCodePro Nerd Font"
 style = "Bold"

[font.italic]
 family = "SauceCodePro Nerd Font"
 style = "Italic"

[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }
